---
- hosts: arista
  connection: network_cli
  remote_user: admin
  become: yes
  become_method: enable
  vars:
    ansible_network_os: "eos"
  tasks:
    - nxos_user:
        aggregate:
          - name: ansibletest1
          - name: ansibletest2
          - name: ansibletest3
